### ISSUE TITLE
Support rendering in kitty terminal

### ISSUE THREAD

**Issue by TanvirOnGH** [lusingander/serie#31]
terminal: [kitty](https://github.com/kovidgoyal/kitty)

On kitty terminal, it's basically blank:

![image](https://github.com/user-attachments/assets/2d902223-9446-45b0-8e3f-1f61b990f447)

**Comment by alerque** [comment]
As of the last tagged release `serie` had no detection of terminals. You need to manually run `serie -p kitty` to make it work, or add that to your config file or make an alias.

#23 added detection for Kitty and #24 is set to add Ghostty and Konsole as well. Hopefully these will be in a release soon.

**Comment by alerque** [comment]
@lusingander You're going to alienate your users and contributors if you manage issues like this. Closing this issue is absolutely appropriate since the feature in question is already implemented and the question about how to use it has been answered. The OP even closed it themselves for you. Coming along and remarking it as https://github.com/lusingander/serie/labels/invalid and changing the close status from resolved to not planned is more than a bit passive aggressive and counter productive.

**Comment by lusingander** [comment]
I didn't intend it to have any meaning beyond just being a status for issue management, but it certainly may have given a bad impression.
